project_name        = "iac-demo"
environment         = "dev"
location            = "australiaeast"
vm_size             = "Standard_B2ts_v2"
vnet_address_space  = "10.0.0.0/16"
subnet_prefix       = "10.0.1.0/24"