project_name       = "iac-demo"
environment        = "staging"
location           = "australiaeast"
vm_size            = "Standard_B1s"
vnet_address_space = "10.1.0.0/16"
subnet_prefix      = "10.1.1.0/24"